#!/bin/bash
#
# Author: Ronald Joe Record <ronaldrecord@gmail.com>
#
# See https://developers.google.com/drive/api/v3/ref-search-terms#operators
# for more info on the Google Drive for Developers API (V3)
#
gdinst=`type -p gdrive`
[ "${gdinst}" ] || {
    echo "The 'gdrive' command is not installed or not in the execution PATH"
    echo "Visit https://github.com/prasmussen/gdrive/releases to download"
    echo "a 'gdrive' binary for this platform"
    exit 1
}

GHOM=${HOME}/.gdrive
GDOPTS="--no-header --absolute --max 100 --name-width 0"

[ -f ${GHOM}/gdhome ] || {
    HERE=`pwd`
    while true
    do
        read -p "Initializing gdrive home to ${HERE}. Ok ? ('Y'/'N'): " yn
        case $yn in
            [Yy]*)
                [ -d ${GHOM} ] || mkdir -p ${GHOM}
                echo "GDHOME=${HERE}" > ${GHOM}/gdhome
                break
                ;;
            [Nn]*)
                read -p "Enter your gdrive home: " gdhome
                case ${gdhome} in
                    *)
                        echo "GDHOME=${gdhome}" > ${GHOM}/gdhome
                        ;;
                esac
                break
                ;;
            * )
                echo "Please answer yes or no."
                ;;
        esac
    done
}

. ${GHOM}/gdhome
[ -d ${GDHOME} ] || {
    echo "Cannot locate gdrive home ${GDHOME}"
    echo "Edit ${GHOM}/gdhome and set your local gdrive home"
    exit 1
}
cd ${GDHOME}

# TODO: getopts support for --force and other options

for file in "$@"
do
  recursive=
  pdir=`dirname "${file}"`
  base=`basename "${file}"`
  [ -f "${pdir}"/.folderid ] || continue
  parentid=`cat "${pdir}"/.folderid`
  typ=

  while read match
  do
    id=`echo ${match} | awk ' { print $1 } '`
    [ "${id}" ] || continue
    path=`gdrive info ${id} | grep ^Path: | awk -F ':' ' { print $2 } '`
    # Remove leading and trailing spaces
    path="$(echo -e "${path}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
    [ "${path}" == "${file}" ] && {
      typ=`gdrive info ${id} | grep ^Mime: | awk -F ':' ' { print $2 } '`
      typ="$(echo -e "${typ}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
      echo ${typ} | grep folder > /dev/null && typ="dir"
      break
    }
  done <<< `gdrive list ${GDOPTS} --query " name = '${base}' and parents in '${parentid}'"`
    [ "${typ}" ] || {
      echo "No Google Drive file or folder '${file}' could be located"
      echo "Perhaps it is owned by another user or it does not exist"
      echo "Skipping download"
      exit 1
    }
    [ "${typ}" == "dir" ] && recursive="--recursive"
    gdrive download query --force --path "${pdir}" ${recursive} \
                          " name = '${base}' and parents in '${parentid}'"
done
