#!/bin/bash
#
# Author: Ronald Joe Record <ronaldrecord@gmail.com>
#
# See https://developers.google.com/drive/api/v3/ref-search-terms#operators
# for more info on the Google Drive for Developers API (V3)
#
gdinst=`type -p gdrive`
[ "${gdinst}" ] || {
    echo "The 'gdrive' command is not installed or not in the execution PATH"
    echo "Visit https://github.com/prasmussen/gdrive/releases to download"
    echo "a 'gdrive' binary for this platform"
    exit 1
}

GHOM=${HOME}/.gdrive

[ -f ${GHOM}/gdhome ] || {
    HERE=`pwd`
    while true
    do
        read -p "Initializing gdrive home to ${HERE}. Ok ? ('Y'/'N'): " yn
        case $yn in
            [Yy]*)
                [ -d ${GHOM} ] || mkdir -p ${GHOM}
                echo "GDHOME=${HERE}" > ${GHOM}/gdhome
                break
                ;;
            [Nn]*)
                read -p "Enter your gdrive home: " gdhome
                case ${gdhome} in
                    *)
                        echo "GDHOME=${gdhome}" > ${GHOM}/gdhome
                        ;;
                esac
                break
                ;;
            * )
                echo "Please answer yes or no."
                ;;
        esac
    done
}

. ${GHOM}/gdhome
[ -d ${GDHOME} ] || {
    echo "Cannot locate gdrive home ${GDHOME}"
    echo "Edit ${GHOM}/gdhome and set your local gdrive home"
    exit 1
}
cd ${GDHOME}

maxfiles=100

usage() {
  printf "\nUsage: gdlist [-m maxfiles] [-u] path/to/fileorfolder [file2 ...]"
  printf "\nWhere:"
  printf "\n\t-m 'maxfiles' specifies the maximum number of files to list"
  printf "\n\t\t(default: 100)"
  printf "\n\t-u displays this usage message\n"
  exit 1
}

while getopts "m:u" flag; do
    case $flag in
        m)
            maxfiles=${OPTARG}
            ;;
        u)
            usage
            ;;
    esac
done
shift $(( OPTIND - 1 ))

if [ $# -eq 0 ]
then
    gdrive list --absolute --max ${maxfiles} --name-width 0
else
    for folder in "$@"
    do
        [ -f "${folder}"/.folderid ] || continue
        fid=`cat "${folder}"/.folderid`
        gdrive list --absolute --max ${maxfiles} --name-width 0 \
                    --query " '${fid}' in parents"
    done
fi
